---
## satnogs
mapbox_token: "{{ MAPBOX_TOKEN }}"
mapbox_map_id: "{{ MAPBOX_MAP_ID }}"

secrets:
  - db_prod: "{{ SECRETS_DB_PROD }}"
  - db_dev: "{{ SECRETS_DB_DEV }}"
  - net_prod: "{{ SECRETS_NET_PROD }}"
  - net_dev: "{{ SECRETS_NET_DEV }}"

opbeat_orgid: "{{ OPBEAT_ORGID }}"
opbeat_secret: "{{ OPBEAT_SECRET }}"
opbeat_appid:
  - db_prod: "{{ OPBEAT_APPID_DB_PROD }}"
  - db_dev: "{{ OPBEAT_APPID_DB_DEV }}"
  - net_prod: "{{ OPBEAT_APPID_NET_PROD }}"
  - net_dev: "{{ OPBEAT_APPID_NET_DEV }}"

analytics:
  - db_prod: "{{ ANALYTICS_DB_PROD }}"
  - net_prod: "{{ ANALYTICS_NET_PROD }}"
