---
# tasks file for mariadb
- name: Install MariaDB
  yum: name={{ item }} state=present
  with_items:
    - mariadb
    - mariadb-server
    - mariadb-devel
    - MySQL-python

- name: Copy my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mariadb
  tags:
    - etcmycnf

- name: Ensure MariaDB is started and enabled on boot
  service: name=mariadb state=started enabled=yes

- include: secure-installation.yml
- include: create_databases.yml
