---
- name: Create app directories
  file:
    path: '{{ item }}'
    state: directory
    owner: satnogs
    group: satnogs
    recurse: yes
  with_items:
    - '{{ app_dir }}'
    - '{{ venv_dir }}'

- name: Pull sources from the repository.
  sudo: yes
  sudo_user: satnogs
  git:
    repo: "{{ repo_url }}"
    dest: "{{ app_dir }}"
    version: "{{ repo_branch }}"
    force: yes
    update: yes
  tags:
    - repo
    - app

- name: django | pip install requirements
  sudo_user: satnogs
  pip:
    requirements: "{{ requirements_file }}"
    virtualenv: "{{ venv_dir }}"
    extra_args: "--upgrade"
  changed_when: false
  tags:
    - pip

- name: django | copy env variables
  template:
    src:  'env.j2'
    dest: '{{ app_dir }}/.env'
    owner: satnogs
    group: satnogs
    mode: 0644
  tags:
    - env

- name: django | collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ app_dir }}"
    virtualenv: "{{ venv_dir }}"
    settings: "{{ django_settings }}"
  tags:
    - collectstatic

- name: django | migrate
  django_manage:
    command: migrate
    app_path: "{{ app_dir }}"
    virtualenv: "{{ venv_dir }}"
    settings: "{{ django_settings }}"
  tags:
    - migrate

- name: django | data sync cronjobs
  template:
    src:  'update_data.j2'
    dest: '/etc/cron.hourly/update_data-{{ sitename }}.sh'
    owner: satnogs
    group: satnogs
    mode: 0755
  tags:
    - cron

- name: django | copy gunicorn conf
  template:
    src:  'gunicorn.conf.j2'
    dest: '{{ app_dir }}/gunicorn.conf'
    owner: satnogs
    group: satnogs
    mode: 0644
  tags:
    - gunicorn

- name: Copy nginx conf
  template:
    src:  'nginx_vhost.conf.j2'
    dest: '/etc/nginx/conf.d/satnogs_{{ sitename }}.conf'
    owner: nginx
    group: nginx
    mode: 0644
  tags:
    - nginx

- name: Copy gunicorn systemd service file
  template:
    src:  'gunicorn.service.j2'
    dest: '/etc/systemd/system/gunicorn-{{ sitename }}.service'
    owner: root
    group: root
    mode: 0644
  tags:
    - gunicorn
    - systemd
  notify:
    - daemon reload

- name: opbeat | copy opbeat notify script
  template:
    src:  'opbeat_notify.j2'
    dest: '/usr/local/bin/opbeat_notify_{{ sitename }}.sh'
    owner: satnogs
    group: satnogs
    mode: 0755
  tags:
    - opbeat

- name: Enable gunicorn service
  service: name=gunicorn-{{ sitename }} state=started enabled=yes
  tags:
    - gunicorn
    - systemd

- name: Restart gunicorn and nginx
  service: name=gunicorn-{{ sitename }} state=restarted enabled=yes
  notify:
    - restart nginx
  tags:
    - gunicorn
    - nginx

- name: opbeat | notify opbeat
  shell: /usr/local/bin/opbeat_notify_{{ sitename }}.sh
  args:
    chdir: '{{ app_dir }}'
  tags:
    - opbeat
