---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Ensure MongoDB Server is present
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ rocket_chat_mongodb_packages }}"

- name: Deploy MongoDB service configuration
  template:
    src: "{{ rocket_chat_mongodb_config_template }}"
    dest: /etc/mongod.conf
  notify: Restart the MongoDB service

- meta: flush_handlers

- name: Ensure the MongoDB service is started/enabled
  service: name=mongod state=started enabled=yes
