---
- name: Deploy Nginx configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: rocket_chat.conf.j2, dest: /etc/nginx/conf.d/rocket_chat.conf }
  notify: Reload the Nginx service
