---
- hosts: vm2.satnogs.org
  become: true

  vars:
    var_www: '/var/www/satnogs'
    app_dir: '{{ var_www }}/db/dev/app'
    venv_dir: '{{ var_www }}/db/dev/venv'
    sitename: 'db-dev'
    socket_dir: '/var/run/satnogs/{{ sitename }}.sock'
    pid_file: '/var/run/satnogs/{{ sitename }}.pid'
    requirements_file: '{{ app_dir }}/requirements/production.txt'
    django_settings: 'db.settings.stage'
    gunicorn_workers: 1
    wsgi: 'db.wsgi'
    repo_url: https://github.com/satnogs/satnogs-db
    repo_branch: dev
    db_dev: true
    db_prod: false
    net_dev: false
    net_prod: false

  roles:
    - { role: satnogs, tags: ['db_dev', 'db'] }
