---
- hosts: vm2.satnogs.org
  sudo: true

  vars:
    var_www: '/var/www/satnogs'
    app_dir: '{{ var_www }}/network/dev/app'
    venv_dir: '{{ var_www }}/network/dev/venv'
    sitename: 'network-dev'
    socket_dir: '/var/run/satnogs/{{ sitename }}.sock'
    pid_file: '/var/run/satnogs/{{ sitename }}.pid'
    requirements_file: '{{ app_dir }}/requirements/production.txt'
    django_settings: 'network.settings.stage'
    gunicorn_workers: 1
    wsgi: 'network.wsgi'
    repo_url: https://github.com/satnogs/satnogs-network
    repo_branch: dev
    net_dev: true
    db_dev: false
    db_prod: false
    net_prod: false

  roles:
    - { role: satnogs, tags: ['network_dev', 'network'] }
